### ISSUE TITLE
Would it be possible to build a version for vue3?

### ISSUE THREAD

**Issue by chamby** [vinayakkulkarni/vue-intl-numberformat#38]
No code changes are necessary as this is a trivial component. A dependency update and a rebuild should be needed along with a new major semantic versioned release.

**Comment by vinayakkulkarni** [comment]
> No code changes are necessary as this is a trivial component. A dependency update and a rebuild should be needed along with a new major semantic versioned release.

You may use - https://v-intl.netlify.app/guide/format/number.html

**Comment by chamby** [comment]
Thanks for the alternative
